const { SlashCommandBuilder } = require('discord.js');
const { createCustomEmbed, createErrorEmbed } = require('../../utils/embeds');
const { User, Shift, Warning, Activity } = require('../../database/mongo');

module.exports = {
    data: new SlashCommandBuilder()
        .setName('case_file')
        .setDescription('Generate a highly detailed relational dossier for a specific user')
        .addUserOption(opt => opt.setName('user').setDescription('The user to investigate').setRequired(true)),

    async execute(interaction) {
        try {
            await interaction.deferReply();
            const targetUser = interaction.options.getUser('user');
            const guildId = interaction.guildId;

            const userRecord = await User.findOne({ userId: targetUser.id }).lean();
            if (!userRecord || !userRecord.staff) {
                return interaction.editReply({ embeds: [createErrorEmbed(`No database records exist for **${targetUser.username}**.`)] });
            }

            // 1. Fetch exact warnings
            const warnings = await Warning.find({ userId: targetUser.id, guildId })
                .sort({ createdAt: -1 })
                .limit(3)
                .lean();

            // 2. Fetch trailing shifts
            const shifts = await Shift.find({ userId: targetUser.id, guildId })
                .sort({ startTime: -1 })
                .limit(3)
                .lean();

            // 3. Fetch trailing activities
            const activities = await Activity.find({ userId: targetUser.id, guildId })
                .sort({ createdAt: -1 })
                .limit(5)
                .lean();

            // Construct Warning String
            let warningStr = '✅ *Active Record Clean*';
            if (warnings.length > 0) {
                warningStr = warnings.map(w => {
                    const t = Math.floor(new Date(w.createdAt).getTime() / 1000);
                    return `- <t:${t}:d> | **[${w.severity.toUpperCase()}]** *${w.reason}*`;
                }).join('\n');
            }

            // Construct Shifts String
            let shiftStr = '❌ *No Logged Shifts*';
            if (shifts.length > 0) {
                shiftStr = shifts.map(s => {
                    const t = Math.floor(new Date(s.startTime).getTime() / 1000);
                    if (!s.endTime) return `- <t:${t}:R> | 🟢 **ACTIVE NOW**`;
                    const hrs = Math.floor(s.duration / 3600);
                    const mins = Math.floor((s.duration % 3600) / 60);
                    return `- <t:${t}:d> | ⏱️ \`${hrs}h ${mins}m\``;
                }).join('\n');
            }

            // Construct Activities String
            let activityStr = '❌ *No Recorded Activities*';
            if (activities.length > 0) {
                activityStr = activities.map(a => {
                    const t = Math.floor(new Date(a.createdAt).getTime() / 1000);
                    const type = a.type.toUpperCase();
                    const action = a.data?.action ? `(${a.data.action})` : '';
                    return `- <t:${t}:R> | 🔹 \`${type}\` ${action}`;
                }).join('\n');
            }

            const totalShiftTime = shifts.reduce((acc, s) => acc + (s.duration || 0), 0);
            const totalHrs = Math.floor(totalShiftTime / 3600);
            const trophies = userRecord.staff.trophies || [];

            const embed = await createCustomEmbed(interaction, {
                title: `📁 Certified Case File: ${targetUser.username}`,
                thumbnail: targetUser.displayAvatarURL({ dynamic: true }),
                description: `**ID:** \`${targetUser.id}\`\n**Rank:** \`${userRecord.staff.rank.toUpperCase()}\` | **Points:** \`${userRecord.staff.points}\``,
                branding: { footer: `Dossier Generated by ${interaction.user.tag}` }
            });

            embed.addFields(
                { name: '🚨 Recent Warnings', value: warningStr, inline: false },
                { name: '⏱️ Recent Shifts', value: shiftStr, inline: false },
                { name: '📋 Recent DB Activities', value: activityStr, inline: false },
                { name: '🏅 Relational Metadata', value: `\`Lifetime Hours:\` **${totalHrs}h**\n\`Trophies Unlocked:\` **${trophies.length}**\n\`Current Streak:\` 🔥 **${userRecord.staff.streak || 0}**`, inline: false }
            );

            await interaction.editReply({ embeds: [embed] });

        } catch (error) {
            console.error('Case File Error:', error);
            const errEmbed = createErrorEmbed('An error occurred while generating the user case file.');
            if (interaction.deferred || interaction.replied) {
                await interaction.editReply({ embeds: [errEmbed] });
            } else {
                await interaction.reply({ embeds: [errEmbed], ephemeral: true });
            }
        }
    }
};
